# Generated by Django 5.1 on 2024-08-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id_notificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("mensaje", models.TextField()),
                ("fecha", models.DateField()),
                ("estado", models.CharField(max_length=50)),
            ],
        ),
    ]
