# Generated by Django 5.1 on 2024-08-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("canchas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id_mantenimiento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "id_cancha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canchas.cancha"
                    ),
                ),
            ],
        ),
    ]
