# Generated by Django 5.1 on 2024-08-17 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mantenimiento", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mantenimiento",
            name="estado",
        ),
    ]
