# Generated by Django 5.1 on 2024-08-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cancha",
            fields=[
                ("id_cancha", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50)),
                ("capacidad", models.IntegerField()),
                ("estado", models.CharField(max_length=50)),
            ],
        ),
    ]
