# Generated by Django 5.1 on 2024-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canchas", "0002_alter_cancha_estado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cancha",
            options={"verbose_name_plural": "Canchas"},
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="capacidad",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="cancha",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="cancha",
            name="barrio",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="cancha",
            name="precio_por_hora",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="cancha",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("RESERVADA", "Reservada"),
                    ("MANTENIMIENTO", "Mantenimiento"),
                ],
                default="DISPONIBLE",
                max_length=20,
            ),
        ),
    ]
