# Generated by Django 5.1 on 2024-08-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("canchas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservaConjunta",
            fields=[
                (
                    "id_reserva_conjunta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_grupo", models.CharField(max_length=100)),
                ("numero_participantes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("id_reserva", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "id_cancha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canchas.cancha"
                    ),
                ),
            ],
        ),
    ]
