# Generated by Django 5.1 on 2024-08-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="fecha",
        ),
        migrations.AlterField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[("Disponible", "Disponible"), ("Reservada", "Reservada")],
                default="Disponible",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="hora_fin",
            field=models.TimeField(editable=False),
        ),
    ]
