# Generated by Django 5.1 on 2024-08-17 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0003_remove_reserva_fecha_alter_reserva_estado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="estado",
        ),
    ]
