# Generated by Django 5.1 on 2024-08-17 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canchas", "0003_alter_cancha_options_remove_cancha_capacidad_and_more"),
        ("reservas", "0004_remove_reserva_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColaSolo",
            fields=[
                ("id_cola", models.AutoField(primary_key=True, serialize=False)),
                ("unido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "id_cancha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canchas.cancha"
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["unido_en"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id_notificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("mensaje", models.TextField()),
                ("enviado_en", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
